spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: java_cbs_dev
    password: java_cbs_dev
    url: jdbc:mysql://db.test.yipicha.com:3306/hxg?useSSL=true
eureka:
  healthcheck:
    enabled: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
    status-page-url-path: /${spring.application.name}/health
env:
  env
