spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3378/cloud?useSSL=true
  rabbitmq:
    username: hxb
    password: hxb
    host: 192.168.44.56
    port: 5672

env:
  dev-hooks-file-test-hooks11
