spring:
  session:
    store-type: redis
  application:
    name: wechat-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3378/wechat-server?useSSL=false&allowMultiQueries=true&char&characterEncoding=UTF-8
    username: root
    password: root
  redis:
    password: msyos
    host: 10.102.2.34
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
  rabbitmq:
    username: hxb
    password: hxb
    host: 192.168.44.56
    port: 5672

imooc.security:
  browser:
    #    signInResponseType: REDIRECT
    signInSuccessUrl: http://localhost/index
    signOutUrl: http://localhost/login
    signUpUrl: http://localhost/signUp
    signInPage: http://localhost/login
    session:
      sessionInvalidUrl: http://localhost/login

logging:
  level:
    com.hxg.manage.dao.mapper: debug

server:
  session:
    timeout: 3600000
  port: 7083
  context-path: /wechat-server

outside.imagesPath: G:\
# 发布域名
service.domain: hxiugangwechat.natapp1.cc

env: env